models:
  - name: LogisticRegression_Quick
    class: LogisticRegression
    init_params:
      max_iter: 2000
      random_state: 42
    param_grid:
      C: [0.1, 1.0, 10.0]
      penalty: ["l2"]
      solver: ["liblinear"]

  - name: RandomForest_Quick
    class: RandomForestClassifier
    init_params:
      random_state: 42
    param_grid:
      n_estimators: [100, 200]
      max_depth: [5, 10]
      min_samples_split: [2, 5]

  - name: GradientBoosting_Quick
    class: GradientBoostingClassifier
    init_params:
      random_state: 42
    param_grid:
      n_estimators: [100, 200]
      learning_rate: [0.05, 0.1]
      max_depth: [3, 5]