models:
  - name: XGBoost_Grid
    class: XGBClassifier
    init_params:
      eval_metric: logloss
      random_state: 42
    param_grid:
      learning_rate: [0.01, 0.05, 0.1, 0.2]
      max_depth: [3, 4, 5, 6, 7, 8, 9, 10]
      n_estimators: [100, 200, 300]