models:
  - name: XGBoost_Grid
    class: XGBClassifier
    init_params:
      eval_metric: logloss
      random_state: 42
    param_grid:
      learning_rate: [0.01, 0.05, 0.1, 0.2]
      max_depth: [3, 5, 7, 9]
      min_child_weight: [1, 3, 5]
      gamma: [0, 0.1, 0.2]
      subsample: [0.6, 0.8, 1.0]
      colsample_bytree: [0.6, 0.8, 1.0]
      n_estimators: [100, 200, 300]