apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-mlflow-xgboost
spec:
  supportedModelFormats:
  - name: mlflow
    version: "2"
    autoSelect: true
  containers:
  - name: kserve-container
    image: tharindumlflowacr2f76fa.azurecr.io/mlflow-xgboost-serving:v1.0.0
    env:
    - name: MLSERVER_MODEL_IMPLEMENTATION
      value: mlserver_mlflow.MLflowRuntime
    - name: MLSERVER_HTTP_PORT
      value: "8080"
    - name: MLSERVER_GRPC_PORT
      value: "9000"
    # Added environment variables for model name and URI configuration
    - name: MLSERVER_MODEL_NAME
      value: "$(MODEL_NAME)"
    - name: MLSERVER_MODEL_URI
      value: "/mnt/models"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
  imagePullSecrets:
  - name: acr-secret