# --- PostgreSQL Sub-chart Configuration ---
# Enable the DEPLOYMENT of PostgreSQL via the sub-chart
postgresql:
  enabled: true
  auth:
    # Credentials FOR the PostgreSQL database instance itself
    database: "mlflow_db"                 # <<< Database to create/use
    username: "mlflow_user"                   # <<< User for the database
    password: "mlflow_user@123" # <<< Password for the database user & CHANGE THIS!

# --- Artifact Store Configuration ---
# Configure Azure Blob Storage artifact root using the nested structure
artifactRoot:
  azureBlob:
    enabled: true
    # Fill in your actual Azure Storage details
    container: "artifactroot"             # <<< REPLACE with your container name
    storageAccount: "tharindumlflow3be9ca4d"      # <<< REPLACE with your storage account name
    accessKey: "ugLrB5BkrquADCgGdV+uFy7kQHSrc758EUvB7jpwUQ0fwmkQA5sjs4yI5Z7cGgo21Ld3oUCCoOyo+ASt+pbz6Q=="  # <<< REPLACE with your storage access key
    # path: "" # Optional: if you want artifacts in a subfolder within the container

# --- Service Configuration ---
service:
  type: LoadBalancer
  port: 80 # Port the LoadBalancer listens on


auth:
  enabled: true
  adminUsername: "admin"
  adminPassword: "S3cr3+"