apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  annotations:
    serving.kserve.io/azure-storage-account-name: tharindumlflow615422a9
type: Opaque
stringData:
  AZURE_STORAGE_ACCESS_KEY: __REDACTED__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: default
secrets:
- name: azure-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: adult-income-model
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "https://tharindumlflow615422a9.blob.core.windows.net/artifactroot/1/5b426b4e758a426792dfb4b0b1fa1458/artifacts/model"