apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  annotations:
    serving.kserve.io/azure-storage-account-name: tharindumlflow615422a9
type: Opaque
stringData:
  AZURE_STORAGE_ACCESS_KEY: __REDACTED__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: default
secrets:
- name: azure-secret
imagePullSecrets:
- name: acr-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: adult-income-model
  annotations:
    serving.kserve.io/deploymentMode: Serverless
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      storageUri: "https://tharindumlflow615422a9.blob.core.windows.net/artifactroot/1/5b426b4e758a426792dfb4b0b1fa1458/artifacts/model"
      # Use runtime instead of container override
      runtime: kserve-mlflow-xgboost
      # Added environment variables to pass to the runtime container
      env:
        - name: MODEL_NAME
          value: "adult-income-model"
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      readinessProbe:
        httpGet:
          path: /v2/health/ready
          port: 8080
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: 8080
        initialDelaySeconds: 180
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5